### ISSUE TITLE
AttributeError: 'VaDE' object has no attribute 'module'

### ISSUE THREAD

**Issue by goodman1204** [GuHongyang/VaDE-pytorch#4]
Any one knows this bug?  I just run the original code and show the following bug. 

Traceback (most recent call last):
  File "main.py", line 50, in <module>
    vade.module.pre_train(DL,pre_epoch=50)
  File "/home/shuiqiao/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'VaDE' object has no attribute 'module'
'''

**Comment by GuHY777** [comment]
vade=VaDE(args)
    if args.cuda:
        vade=vade.cuda()
        vade=nn.DataParallel(vade,device_ids=range(4))

I used 4 gpus. 
You should delete
vade=nn.DataParallel(vade,device_ids=range(4))

**Comment by goodman1204** [comment]
Thanks. I just removed the cuda() function and get it  run.
